name: CI
on: push
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v3

      # Install Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Downgrade npm
      - run: |
          npm install -g npm@latest-6

      # Install & test:
      - run: npm ci
      - run: npm test
