name: CI
on: push
env:
  CXX: g++-9
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3

      # Use GCC 9
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      # Install Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Downgrade npm
      - run: npm install -g npm@latest-6
        if: ${{ matrix.node-version != '20.x' }}

      # Install & test:
      - run: git submodule update --init
      - run: npm install
      - run: npm test
